<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWcH806V\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWcH806V/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerWcH806V.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerWcH806V\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerWcH806V\appAppKernelProdContainer([
    'container.build_hash' => 'WcH806V',
    'container.build_id' => 'e28619cf',
    'container.build_time' => 1706609911,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWcH806V');
