<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOLpZOjG\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOLpZOjG/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerOLpZOjG.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerOLpZOjG\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerOLpZOjG\appAppKernelProdContainer([
    'container.build_hash' => 'OLpZOjG',
    'container.build_id' => '0f9a510f',
    'container.build_time' => 1707841051,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOLpZOjG');
