// @ts-check
const { test, expect } = require('@playwright/test');
const path = require('path');
const fakeslip = path.join(__dirname, 'fakeslip.png');   
const slip = path.join(__dirname, 'slip.jpg');   

test('US01 : ซื้อบัตรกำนัน | TC01', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160416');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').dblclick();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('ชำระผ่านเคาท์เตอร์เซอร์วิส').check();
  await page.getByLabel('ฉันยอมรับ ข้อกำหนดในการให้บริการ และจะปฏิบัติตามอย่างไม่มีเงื่อนไข').check();
  await page.getByRole('button', { name: 'สั่งซื้อ' }).click();
  await page.getByRole('heading', { name: ' ยืนยันการสั่งซื้อของคุณแล้ว' }).click();
});

test('US01 : ซื้อบัตรกำนัน | TC02', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('ชำระผ่านเคาท์เตอร์เซอร์วิส').check();
  await page.getByLabel('ฉันยอมรับ ข้อกำหนดในการให้บริการ และจะปฏิบัติตามอย่างไม่มีเงื่อนไข').check();
  await page.getByRole('button', { name: 'สั่งซื้อ' }).click();
  await page.getByRole('heading', { name: ' ยืนยันการสั่งซื้อของคุณแล้ว' }).click();
});


test('US02 : กรอกข้อมูล | TC03', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('sgmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
});

test('US02 : กรอกข้อมูล | TC04', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('sgmail@com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByText('Invalid format.').click();
});

test('US03 : วิธีการชำระเงิน | TC05', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160461');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').click();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('ชำระผ่านบัญชีธนาคาร').check();
  await page.getByText('หมายเลขบัญชี: 1-122-334-4556-').click();
});

test('US03 : วิธีการชำระเงิน | TC06', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160461');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').click();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByText('ชำระผ่านพร้อมเพย์').click();
  await page.getByRole('img', { name: 'QR Code' }).click();
});

test('US03 : วิธีการชำระเงิน | TC07', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160461');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').click();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByText('ชำระผ่านพร้อมเพย์').click();
  await page.getByRole('img', { name: 'QR Code' }).click();
});

test('US04 : อัพโหลดใบเสร็จ | TC08', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160461');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').click();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('ชำระผ่านบัญชีธนาคาร').check();
  await page.getByRole('textbox').setInputFiles(slip);
  await page.getByRole('button', { name: 'ตรวจสอบ' }).click();
  await page.getByRole('heading', { name: ' ยืนยันการสั่งซื้อของคุณแล้ว' }).click();
});

test('US04 : อัพโหลดใบเสร็จ | TC09', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160461');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').click();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('ชำระผ่านบัญชีธนาคาร').check();
  await page.getByRole('textbox').setInputFiles(fakeslip);
  await page.getByRole('button', { name: 'ตรวจสอบ' }).click();
  await page.getByRole('heading', { name: 'ชำระเงิน' }).click();
});

test('US04 : อัพโหลดใบเสร็จ | TC10', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160461');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').click();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByText('ชำระผ่านพร้อมเพย์').click();
  await page.getByRole('textbox').setInputFiles(slip);
  await page.getByRole('button', { name: 'ตรวจสอบ' }).click();
  await page.getByRole('heading', { name: ' ยืนยันการสั่งซื้อของคุณแล้ว' }).click();
});

test('US04 : อัพโหลดใบเสร็จ | TC11', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160461');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').click();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByText('ชำระผ่านพร้อมเพย์').click();
  await page.getByRole('textbox').setInputFiles(fakeslip);
  await page.getByRole('button', { name: 'ตรวจสอบ' }).click();
  await page.getByRole('heading', { name: 'ชำระเงิน' }).click();
});

test('US05 : ดาวน์โหลดใบกำกับภาษี | TC12', async ({ page }) => {
  await page.goto('http://localhost:8080/th/');
  await page.locator('article').filter({ hasText: ' เปิดหน้าต่างย่อ บัตรกำนัล ฿100.00 ใหม่' }).getByRole('link').first().click();
  await page.getByRole('button', { name: ' หยิบใส่ตะกร้า' }).click();
  await page.getByRole('link', { name: ' ทำรายการชำระเงิน' }).click();
  await page.getByRole('link', { name: 'ทำรายการชำระเงิน' }).click();
  await page.getByLabel('ชื่อ').click();
  await page.getByLabel('ชื่อ').fill('สมใจ');
  await page.getByLabel('นามสกุล').click();
  await page.getByLabel('นามสกุล').fill('สวัสดี');
  await page.getByLabel('อีเมลล์').click();
  await page.getByLabel('อีเมลล์').fill('s@gmail.com');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').click();
  await page.getByLabel('หมายเลขประจำตัวผู้เสียภาษี').fill('0994000160461');
  await page.getByLabel('ที่อยู่', { exact: true }).click();
  await page.getByLabel('ที่อยู่', { exact: true }).fill('123/11');
  await page.getByLabel('จังหวัด').click();
  await page.getByLabel('จังหวัด').fill('ขอนแก่น');
  await page.getByLabel('รหัสไปรษณีย์').click();
  await page.getByLabel('รหัสไปรษณีย์').fill('40000');
  await page.getByLabel('โทรศัพท์').click();
  await page.getByLabel('โทรศัพท์').fill('0806123456');
  await page.getByRole('button', { name: 'ทำต่อ' }).click();
  await page.getByLabel('ชำระผ่านเคาท์เตอร์เซอร์วิส').check();
  await page.locator('#conditions-to-approve div').filter({ hasText: 'ฉันยอมรับ ข้อกำหนดในการให้บริการ และจะปฏิบัติตามอย่างไม่มีเงื่อนไข' }).click();
  await page.getByRole('button', { name: 'สั่งซื้อ' }).click();
  await page.getByText('อีเมลถูกส่งไปยังที่อยู่ s@').click();
});
